## 학습내용
- 예외

### 예외
자바에서 예외는 "우리가 예상한, 혹은 예상치도 못한 일이 발생하는 것을 미리 예견하고 안전장치를 하는 것"을 말한다. <br>
자바에서는 예상을 했든, 하지 않았건, 예외적인 일이 발생하게 되면 "예외"라는 것을 던져버린다.

### try-catch
```java
public class ExceptionSample {
    public static void main(String[] args) {
        ExceptionSample sample = new ExceptionSample();
        sample.arrayOutOfBoundTryCatch();
    }
    // 예외가 발생
    public void arrayOutOfBound(){
        int[] intArray = new int[5];
        System.out.println(intArray[5]);
    }
    // 예외를 발생시 처리법 try-catch
    public void arrayOutOfBoundTryCatch(){
        int[] intArray = new int[5];
        try {
            System.out.println("이건실행되겠지");
            System.out.println(intArray[5]);
            System.out.println("This code should run");
        } catch (Exception e){
            System.err.println("Exception occured");
        }
        System.out.println("This code must run");

    }
}
```
try뒤에 중괄호로 예외가 발생하는 문장들을 묶어 주고, catch괄호 안에 예외가 발생했을 때 처리를 해준다. <br>
모든 문장을 묶을필요는 없고, 예외가 발생하는 부분만 묶어주면 된다. <br>
<code>System.err.println("Exception occured"); </code> 여기서 catch문 안에 <code>System.out</code>이 아니라 <code>System.err</code>로 다르게 넣었는데 개발 도구에서 IDE에서는 출력결과가 다른 색으로 표시된다.<br>

### try블록 내에서 예외 발생
try블록 내에서 예외 발생하면, 예외가 발생한 줄 이후에 있는 try블록 내의 코드들은 수행되지 않는다. <br>
그 다음에 catch 블록에 있는 문장이 실행된다. 다시 말해서, try블록 내에서 예외가 발생하지 않으면 catch내에 있는 코드는 실행되지 않는다.

### try-catch정리
- try-catch에서 예외가 발생하지 않을 경우 <pre>try내에 있는 모든 문장이 실행되고 try-catch 문장 이후의 내용이 실행된다. </pre>
- try-catch에서 예외가 발생하는 경우 <pre> 
try내에서 예외가 발생한 이후의 문장들은 실행되지 않는다. 
catch 내에 있는 문장을 반드시 실행되고, try-catch문장 이후의 내용이 실행된다.
</pre>
- 변수선언은 지역번수로 try블록 내에서 선언한 변수를 catch에서 사용할 수 없다. 그래서 catch문장에서 사용할 변수에 대해서는 try앞에 미리 선언해 놓는다.

### finally
자바에서 예외를 처리할 때의 finally는 "어떠한 경우에도 넌 반드시 실행해 라는" 의미다.<br>
```java
public class FinallySample {
    public static void main(String[] args) {
        FinallySample sample = new FinallySample();
        sample.finallySample();
    }

    public void finallySample(){
        int[] intArray = new int[5];
        try{
            System.out.println(intArray[5]);
        }catch (Exception e){
            System.err.println(intArray.length);
        } finally { // 예외가 발생하든 안하든 꼭 실행되어야하는 부분
            System.out.println("Here is finally");
        }
        System.out.println("This code must run");
    }
}
```
<pre>
5
Here is finally
This code must run
</pre>
이처럼 finally블록은 예외 발생 여부와 상관 없이 실행된다. "그런데 이걸 어디다가 써?" <br>
finally블록은 코드의 중복을 피하기 위해서 반드시 필요하다.

### 두 개 이상의 catch
try는 한 번만 쓰고, catch블록을 여러 개 만들어도 전혀 문제 없다. <br>
그런데 catch블록의 순서는 매우 중요하다. catch블록은 순서를 따진다.
```java
public class MultiCatchSample {
    public static void main(String[] args) {
        MultiCatchSample sample = new MultiCatchSample();
        sample.multiCatch();
    }

    public void multiCatch(){
        int[] intArray = new int[5];
        try{
            System.out.println(intArray[5]);
        }catch (NullPointerException e){
            System.err.println("NullPointerException occured");
        }
        catch (ArrayIndexOutOfBoundsException e){
            System.err.println("ArrayIndexOutOfBoundsException occured");
        }
        catch (Exception e){ // 애가 맨 위로 간다면 ArrayIndexOutOfBoundsException가 필요없어진다. 그래서 컴파일오류가 난다.
            System.err.println(intArray.length);
        }
    }
}

```
예외는 부모 예외 클래스가 이미 catch를 하고, 자식 클래스가 그 아래에서 catch를 하도록 되어 있을 경우에는 자식 클래스가 예외를 처리할 기회가 없다.
catch문을 사용할 때에는 Exception클래스로 catch하는 것을 가장 아래에 추가할 것을 권장한다. <br>
따라서 가장 마지막 catch블록은 Exception 클래스를 선언하여 예외들이 빠져 나가지 않게 꽁꽁 묶어 주는 것이 좋다.

### 정리
- try다음에 오는 catch블록은 1개 이상 올 수 있다.
- 먼저 선언한 catch블록의 예외 클래스가 다음에 선언한 catch블록의 부모에 속하면, 자식에 속하는 catch블록은 절대 실행될 일이 없으므로 컴파일이 되지 않는다.
- 하나의 try블록에서 예외가 발생하면 그 예외와 관련이 있는 catch 블록을 찾아서 실행한다.
- catch블록 중 발생한 예외와 관련있는 블록이 없으면, 예외가 발생되면서 해당 쓰레드는 끝난다. 따라서, 마지막 catch블록에는 Exception클래스로 묶어주는 버릇을 들여 놓아야 안전한 프로그램이 될 수 있다. 

### 예외 종류
- checked exception 우리가 흔히사용하는거
- error
- runtime exception 혹은 unchecked exception (런타임 예외는 예외가 발생할 것을 미리 감지하지 못했을 때 발생한다. 실행시에는 발생할 가능성이 있다.)
<img src="https://user-images.githubusercontent.com/79621675/150474214-cd907384-fd1f-45fa-af39-108edc6b865c.png" width="400">
여기서 Exception을 바로 확장한 클래스들이 Checked이며, RuntimeException 밑에 확장 되어 있는 클래스들이 런타임 예외들이다.


### Throwable 클래스 메소드
Exception과 Error클래스는 Throwable클래스를 상속받아 처리하도록 되어 있다.
Throwalbe클래스에 선언된 몇몇 메소드
- getMessage()
- toString()
- printStackTrace()

### throws
catch에 해당하는 예외가 없다면 발생된 예외는 메소드 밖으로 던져버린다. 즉 다시 말해서 에외가 발생된 메소드를 호출한 메소드로 던진다는 의미다.
```java
public class ThrowableSample {
    public static void main(String[] args) {
        ThrowableSample sample = new ThrowableSample();
//        sample.throwable();
        try{
            sample.throwException(13);
        } catch (Exception e){
            e.printStackTrace();
        }

    }


    public void throwException(int number) throws Exception{
        if(number>12){
                throw new Exception("Number is over than 12");
            }
    }
```
이렇게 선언해놓으면 예외가 발생할때 try-catch로 묶어주지 않아도 그 메소드를 호출한 메소드로 예외 처리를 위임하는것이어서 문제가 되지 않는다. 대신 호출한 부분에서 try-catch로 감싸주어야한다.

### throws와 throw 정리 P363

### 사용자 정의 예외
예외 클래스를 직접 개발자가 만들수있지만, 단 한 가지 조건으로 Throwable이나 그 자식 클래스의 상속을 받아야만 한다는 것이다. Thorwable클래스의 상속을 받아도 되지만, Exception을 처리하는 클래스라면
java.lang.Exception클래스의 상속을 받는 것이 좋다. (내가 프로젝트에 했던것은 IllegalException)
```java
public class MyException extends Exception{ // 상속이다 다르게 생각x 

    public MyException(){ 
        super();
    }

    public MyException(String message){
        super(message);
    }
}
```

### 자바 예외 처리 전략 P367
예외를 만들경우 Excpetion으로 항상만들지 말고, 예외가 항상 발생하지 않고 실행시에 발생할 확률이 높은 경우에는 런타임 예외로 만드는 것이 나을 수도 있다.
즉, 클래스 선언시 extends Exception 대신에 extends RuntimeException으로 선언하는 것이다. 이렇게 되면 또 컴파일시에 예외가 발생하지 않는다. <br>
이 경우네는 예외가 발생할 경우 해당 클래스를 호출하는 다른 클래스에서 예외를 처리하도록 구조적인 장치가 되어야한다. 
구조적인 장치란 try-catch로 묶지 않은 메소드를 호출하는 메소드에서 예외를 처리하는 try-catch가 되어 있어야한다는것이다.

### 정리
- 임의의 예외 클래스 만들시에는 반드시 try-catch묶어줄 필요가 있을 경우에만 Exception 클래스를 확장한다. 일반적으로 실행시 예외를 처리할 수 있는 경우에는 RuntimeException 클래스를 확장을 권장 (즉 실행시와 항상 발생하는경우를 나누어라)
- catch문 내에 아무런 작업 없이 공백을 놔두면 예외 분석이 어려워지므로 꼭 로그 처리와 같은 예외 처리를 해줘야만 한다.


